name: Build Build Server

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-build-server:
    runs-on: ubuntu-latest

    defaults:
        run:
          working-directory: infra/build_server

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc zip

      - name: Build release binaries
        run: make package

      - name: Upload release artifact
        uses: actions/upload-artifact@v4
        with:
          name: webcat-build-server
          path: dist/webcat-build-server.zip